name: vfs
description: Virtual file system for testin dart code.
version: 0.0.1
repository: https://github.com/miomit/vfs

environment:
  sdk: ^3.4.3

dependencies:
  path: ^1.8.0
  graph_dot: ^1.0.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
